config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments, only: [:create]
  end

  get '/login', to: 'login#new'
  post '/login', to: 'login#create'
  delete '/logout', to: 'login#destroy'

  get '/register', to: 'register#new'
  post '/register', to: 'register#create'

  get '/forgot_password', to: 'password_resets#new'
  post '/forgot_password', to: 'password_resets#create'
  get '/reset_password/:token', to: 'password_resets#edit', as: 'reset_password'
  patch '/reset_password/:token', to: 'password_resets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :articles

    validates :name, presence: true
    validates :name_user, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
  
    private
  
    def require_login
      unless current_user
        flash[:alert] = "Você precisa fazer login para acessar esta página."
        redirect_to login_path
      end
    end
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    helper_method :current_user
  end
  

app/controllers/articles_controller.rb
# app/controllers/articles_controller.rb 
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @articles = Article.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: "Artigo criado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: "Artigo atualizado com sucesso!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, notice: "Artigo excluído com sucesso!"
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:create]
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)

    if current_user
      @comment.author_name = current_user.name_user
    else
      @comment.author_name = params[:author_name] || "Anônimo"
    end

    if @comment.save
      redirect_to @article, notice: "Comentário enviado com sucesso!"
    else
      redirect_to @article, alert: "Falha ao enviar o comentário."
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/login_controller.rb
# app/controllers/login_controller.rb

class LoginController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Login bem-sucedido!"
    else
      flash.now[:alert] = "Combinação de e-mail/senha inválida"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logout realizado com sucesso!"
  end
end

app/controllers/password_resets_controller.rb
# app/controllers/password_resets_controller.rb

class PasswordResetsController < ApplicationController
    skip_before_action :require_login
  
    def new
    end
  
    def create
      user = User.find_by(email: params[:email])
      if user
        user.generate_password_reset_token!
        # Aqui você pode enviar um e-mail com instruções para redefinir a senha
        redirect_to root_path, notice: "E-mail de recuperação de senha enviado com sucesso!"
      else
        flash.now[:alert] = "Usuário não encontrado."
        render :new
      end
    end
  
    def edit
      @user = User.find_by(password_reset_token: params[:token])
      if @user
        # Aqui você renderiza o formulário para redefinir a senha
      else
        redirect_to root_path, alert: "Token de recuperação de senha inválido."
      end
    end
  
    def update
      @user = User.find_by(password_reset_token: params[:token])
      if @user&.update(password: params[:password], password_confirmation: params[:password_confirmation])
        redirect_to login_path, notice: "Senha redefinida com sucesso. Faça login com sua nova senha."
      else
        render :edit
      end
    end
  end
  

app/controllers/register_controller.rb
# app/controllers/register_controller.rb

class RegisterController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "Usuário criado com sucesso. Por favor, faça login."
    else
      flash.now[:alert] = "Ocorreram erros ao criar o usuário."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<!-- app/views/articles/index.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Blog Wesley</title>
  <style>
    body {
      background-color: #222;
      color: #fff;
      font-family: Arial, sans-serif;
      padding: 20px;
    }
    h1 {
      color: #f00;
    }
    ul {
      list-style: none;
      padding: 0;
    }
    li {
      margin-bottom: 20px;
    }
    a {
      color: #00f;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <h1>Blog Wesley</h1>

  <ul>
    <% @articles.each do |article| %>
      <li>
        <h2><%= article.title %></h2>
        <p><%= article.body %></p>
        <p><a href="<%= article_path(article) %>">Veja mais</a></p>
      </li>
    <% end %>
  </ul>

  <%= will_paginate @articles %>

  <%= link_to "New Article", new_article_path %>

  <p>Direitos reservados.</p>
</body>
</html>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Postar" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1>Pagina saiba mais sobre o post</h1>

<h2><%= @article.title %></h2>

<p><%= @article.body %></p>



<h2>Comments</h2>
<% if @article.comments.any? %>
  <% @article.comments.each do |comment| %>
    <p>
      <strong>Author:</strong>
      <%= comment.author_name %>
    </p>

    <p>
      <strong>Comentario:</strong>
      <%= comment.body %>
    </p>
  <% end %>
<% else %>
  <p>Nenhum comentário</p>
<% end %>


<%= render "comment/form", comments: @comment %>

<% if current_user %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
<% else %>

<% end %>

app/views/comment/_form.html.erb
<h2>Add a comment:</h2>
<%= form_with(model: [@article, @comment]) do |form| %>
  <% if current_user %>
    <p>Logado como: <%= current_user.name_user %></p>
  <% else %>
    <div class="field">
      <%= form.label :author_name, "Nome (opcional)" %>
      <%= form.text_field :author_name, placeholder: "Seu nome (opcional)" %>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :body, "Comentário" %>
    <%= form.text_area :body, placeholder: "Digite seu comentário aqui" %>
  </div>
  <div class="actions">
    <%= form.submit "Enviar Comentário" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Wesley</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/_form.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>


<%= form_with(url: login_path) do |form| %>
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
  
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
  
    <div class="actions">
      <%= form.submit "Login" %>
    </div>
  <% end %>
  

app/views/login/index.html.erb
<!-- app/views/login/new.html.erb -->
<h1>Login</h1>

<%= form_with(url: login_path, local: true) do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>
  
  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Login" %>
  </div>
<% end %>

<p>
  <%= link_to "Não tem uma conta? Registre-se aqui", register_path %>
</p>

app/views/register/_new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: user, url: register_path) do |form| %>
  <%= form.label :nome%>
  <%= form.text_field :name %>

  <%= form.label :nome_usuario %>
  <%= form.text_field :name_user %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.submit 'Cadastrar' %>
<% end %>

app/views/register/index.html.erb
<h1>Register</h1>

<%= render 'register/new', user: @user %>

<p>
    <%= link_to "Já tem uma conta ? Faça o login", login_path %>
</p>